site_name: qi - Git Repository Script Manager
site_description: A Linux command line tool that manages a cache of remote git repositories and allows you to
  quickly execute bash scripts from them by name.
site_author: qi Project
site_url: https://yjmrobert.github.io/qi/

repo_name: yjmrobert/qi
repo_url: https://github.com/yjmrobert/qi
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Quick Start: quickstart.md
  - User Guide:
      - Basic Usage: usage/basic.md
      - Commands: usage/commands.md
      - Configuration: usage/configuration.md
      - Troubleshooting: usage/troubleshooting.md
  - Development:
      - Contributing: development/contributing.md
      - Testing: development/testing.md
      - Architecture: development/architecture.md
  - API Reference:
      - Library Functions: api/library.md
      - Configuration Options: api/config.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yjmrobert/qi
